# Generated by Django 2.0.3 on 2018-04-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convidados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='photo',
            new_name='convite',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='nome',
        ),
    ]
